services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    env_file:
      - .env  
    volumes:
      - ./backend:/app  
    restart: always

  frontend:
    build: ./frontend/vite-project
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_URL=http://backend:5001
    depends_on:
      - backend
