// import { test, expect } from '@playwright/test';

// test('test', async ({ page }) => {
//   await page.goto('http://localhost:5173/');
//   await page.getByRole('button', { name: 'Log In' }).click();
//   await page.getByRole('textbox', { name: 'Enter your email' }).click();
//   await page.getByRole('textbox', { name: 'Enter your email' }).fill('haoding2455@gmail.com');
//   await page.getByRole('textbox', { name: 'Enter your password' }).click();
//   await page.getByRole('textbox', { name: 'Enter your password' }).fill('Qaz454564545');
//   await page.getByRole('textbox', { name: 'Enter your password' }).press('Enter');
//   await page.getByRole('button', { name: 'Login' }).click();
//   await page.getByRole('button', { name: 'View' }).click();
//   await page.getByRole('button', { name: 'bar-chart Details' }).nth(1).click();
//   await page.getByLabel('Close', { exact: true }).click();
//   await page.getByRole('columnheader', { name: 'Date' }).locator('div').first().click();
//   await page.getByRole('columnheader', { name: 'Date' }).locator('div').first().click();
//   await page.getByRole('columnheader', { name: 'Date' }).locator('div').first().click();
//   await page.getByRole('columnheader', { name: 'Date' }).locator('div').first().click();
//   await page.getByRole('button', { name: 'eye View' }).nth(1).click();
//   await page.locator('.ant-btn').first().click();
//   await page.getByRole('button', { name: 'Generate AI Response' }).first().click();
//   await page.getByRole('button', { name: 'Generate AI Response' }).first().click();
//   await page.getByRole('button', { name: 'Generate AI Response' }).first().click();
//   await page.getByRole('button', { name: 'Generate AI Response' }).first().click();
//   await page.getByRole('button', { name: 'Back to History' }).click();
//   await page.getByRole('textbox', { name: 'Search interviews' }).click();
//   await page.getByRole('textbox', { name: 'Search interviews' }).fill('');
//   await page.getByRole('textbox', { name: 'Start date' }).click();
//   await page.getByRole('textbox', { name: 'Start date' }).fill('4');
//   await page.getByTitle('-04-11').locator('div').click();
//   await page.getByRole('textbox', { name: 'End date' }).click();
//   await page.getByTitle('-05-15').click();
//   await page.getByRole('textbox', { name: 'Start date' }).click();
//   await page.getByTitle('-04-02').locator('div').click();
//   await page.getByText('8', { exact: true }).nth(2).click();
//   await page.locator('#rc_select_3').click();
//   await page.getByTitle('Voice').locator('div').click();
//   await page.getByRole('button', { name: 'Back to Dashboard' }).click();
//   await page.getByTestId('logout-button').click();
// });