// import { test, expect } from '@playwright/test';

// test('test', async ({ page }) => {
//   await page.getByRole('button', { name: 'Log In' }).click();
//   await page.getByRole('textbox', { name: 'Enter your email' }).click();
//   await page.getByRole('textbox', { name: 'Enter your email' }).fill('haoding2455@gmail.com');
//   await page.getByRole('textbox', { name: 'Enter your password' }).click();
//   await page.getByRole('textbox', { name: 'Enter your password' }).fill('Qaz454564545');
//   await page.getByRole('textbox', { name: 'Enter your password' }).press('Enter');
//   await page.getByRole('button', { name: 'Login' }).click();
//   await page.getByRole('button', { name: 'Start Now' }).click();
//   await page.getByRole('button', { name: 'Create Custom Interview' }).click();
//   await page.getByTestId('interview-name-input').click();
//   await page.getByTestId('interview-name-input').fill('hello');
//   await page.getByTestId('company-name-input').click();
//   await page.getByTestId('company-name-input').fill('');
//   await page.getByTestId('interview-name-input').click();
//   await page.getByTestId('company-name-input').click();
//   await page.getByTestId('company-name-input').fill('openai');
//   await page.getByTestId('save-update-button').click();
//   await page.locator('div').filter({ hasText: /^DOTACompany: ValveQuestion Type: technicalInterview Type: voice$/ }).nth(1).click();
//   await page.getByTestId('config-menu-button').nth(1).click();
//   await page.getByTestId('config-menu-button').nth(2).click();
//   await page.getByTestId('edit-config-button').click();
//   await page.locator('div').filter({ hasText: /^Question Type \*BehavioralTechnical$/ }).getByRole('combobox').selectOption('technical');
//   await page.getByTestId('save-update-button').click();
//   await page.getByTestId('config-menu-button').nth(2).click();
//   await page.getByTestId('edit-config-button').click();
//   await page.getByTestId('interview-name-input').click();
//   await page.getByTestId('interview-name-input').fill('a job');
//   await page.getByTestId('save-update-button').click();
//   await page.getByText('Company: openaiQuestion Type').click();
//   await page.getByRole('button', { name: 'Start Interview with Selected' }).click();
//   await page.getByRole('textbox', { name: 'Type your response...' }).click();
//   await page.getByRole('textbox', { name: 'Type your response...' }).fill('thanks');
//   await page.getByRole('button', { name: 'End Interview' }).click();
//   await page.locator('div').filter({ hasText: /^I did a double check with another algorithmGenerate AI Response$/ }).getByRole('button').click();
//   await page.locator('div').filter({ hasText: /^I use the api of LLM modelsGenerate AI Response$/ }).getByRole('button').click();
//   await page.getByRole('button', { name: 'Generate AI Response' }).nth(1).click();
//   await page.getByRole('button', { name: 'Back to History' }).click();
//   await page.getByRole('button', { name: 'bar-chart Details' }).nth(3).click();
//   await page.getByRole('button', { name: 'View Interview' }).click();
//   await page.getByRole('button', { name: 'Back to History' }).click();
//   await page.getByRole('button', { name: 'delete Delete' }).first().click();
//   await page.getByRole('button', { name: 'Cancel' }).click();
//   await page.getByRole('button', { name: 'delete Delete' }).first().click();
//   await page.getByRole('button', { name: 'Yes, Delete' }).click();
//   const page1Promise = page.waitForEvent('popup');
//   await page.getByRole('button', { name: 'export Export' }).nth(1).click();
//   const page1 = await page1Promise;
// });