name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      # Install dependencies in both frontend and backend
      - name: Install frontend dependencies
        run: |
          cd frontend/vite-project
          pnpm install
      
      - name: Install backend dependencies
        run: |
          cd backend
          poetry install

      # Start the backend server in the background
      - name: Start Backend Server
        run: |
          cd backend
          poetry run python app.py
      
      # Start the frontend server in the background (assuming Vite default port 5173)
      - name: Start Frontend Server
        run: |
          cd frontend/vite-project
          pnpm run dev
      
      # Wait a few seconds to ensure both servers have time to start up.
      - name: Wait for servers to be ready
        run: sleep 10
      
      - name: Install Playwright Browsers
        run: |
          cd frontend/vite-project
          pnpm exec playwright install --with-deps
      
      - name: Run Playwright tests
        run: |
          cd frontend/vite-project
          pnpm exec playwright test
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
