name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # 1. Check out the repository code.
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js (for frontend tasks).
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 3. Set up Python (for backend tasks).
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Adjust as needed
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
  
      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm
  
      # Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install

      # 5. Install dependencies for the backend.
      - name: Install Backend Dependencies
        run: |
          cd backend
          poetry install

      # 6. Start backend server in the background.
      - name: Start Backend Server
        run: |
          cd backend
          nohup poetry run python app.py &

      # 7. Start frontend server in the background.
      - name: Start Frontend Server
        run: |
          cd frontend/vite-project
          nohup pnpm run dev &

      # 8. Wait until both servers are likely up.
      - name: Wait for servers to be ready
        run: sleep 10
        # Alternatively, consider using a tool like "wait-on" for a more robust check.

      # 9. Run backend tests (if you have tests set up using pytest or similar).
      - name: Run Backend Tests
        run: |
          cd backend
          poetry run pytest

      # 10. Install Playwright browsers.
      - name: Install Playwright Browsers
        run: |
          cd frontend/vite-project
          pnpm exec playwright install --with-deps

      # 11. Run Playwright tests.
      - name: Run Playwright Tests
        run: |
          cd frontend/vite-project
          pnpm exec playwright test

      # 12. Upload test reports as artifacts.
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            backend/test-reports/
            frontend/vite-project/playwright-report/

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test
    # Only deploy on main branch if tests succeed.
    if: github.ref == 'refs/heads/main' && success()
    steps:
      # 1. Check out the repository code.
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Build and deploy the frontend.
      - name: Build Frontend
        run: |
          cd frontend/vite-project
          pnpm run build
      - name: Deploy Frontend
        run: |
          echo "Deploying frontend..."
          # Replace this with your actual frontend deployment commands.

      # 3. Deploy the backend.
      - name: Deploy Backend
        run: |
          cd backend
          echo "Deploying backend..."
          # Replace this with your actual backend deployment commands.
